name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  lint:
    name: Lint add-on
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4

      - name: 🚀 Run Home Assistant Add-on Lint
        uses: frenck/action-addon-linter@v2.17
        with:
          path: "./wmbusmeters-ha-addon-edge"
